package POJOS;
// Generated 23-abr-2020 19:09:23 by Hibernate Tools 4.3.1



/**
 * EmpleDepartId generated by hbm2java
 */
public class EmpleDepartId  implements java.io.Serializable {


     private int id;
     private String nif;
     private String nombre;
     private String apellidos;
     private String descripcion;
     private String localizacion;

    public EmpleDepartId() {
    }

    public EmpleDepartId(int id, String nif, String nombre, String apellidos, String descripcion, String localizacion) {
       this.id = id;
       this.nif = nif;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.descripcion = descripcion;
       this.localizacion = localizacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleDepartId) ) return false;
		 EmpleDepartId castOther = ( EmpleDepartId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getNif()==castOther.getNif()) || ( this.getNif()!=null && castOther.getNif()!=null && this.getNif().equals(castOther.getNif()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getApellidos()==castOther.getApellidos()) || ( this.getApellidos()!=null && castOther.getApellidos()!=null && this.getApellidos().equals(castOther.getApellidos()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getLocalizacion()==castOther.getLocalizacion()) || ( this.getLocalizacion()!=null && castOther.getLocalizacion()!=null && this.getLocalizacion().equals(castOther.getLocalizacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getNif() == null ? 0 : this.getNif().hashCode() );
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getApellidos() == null ? 0 : this.getApellidos().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getLocalizacion() == null ? 0 : this.getLocalizacion().hashCode() );
         return result;
   }   


}


