package POJOS;
// Generated 23-abr-2020 19:09:23 by Hibernate Tools 4.3.1



/**
 * EmpleDepart generated by hbm2java
 */
public class EmpleDepart  implements java.io.Serializable {


     private EmpleDepartId id;

    public EmpleDepart() {
    }

    public EmpleDepart(EmpleDepartId id) {
       this.id = id;
    }
   
    public EmpleDepartId getId() {
        return this.id;
    }
    
    public void setId(EmpleDepartId id) {
        this.id = id;
    }




}


